[dashhaorch]: Fix error: stack protector not protecting local variables: variable length buffer (#3643)
GCC error:

g++ -DHAVE_CONFIG_H -I. -I.. -I ../lib -I .. -I ../warmrestart -I switch -I flex_counter -I debug_counter -I port -I pbh -I nhg -g -DNDEBUG  -std=c++14 -Wall -fPIC -Wno-write-strings -I/usr/include/swss -I/usr/include -I/usr/include/libnl3 -Werror -Wno-reorder -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Wextra -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wlong-long -Wmissing-field-initializers -Wmissing-format-attribute -Wno-aggregate-return -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvariadic-macros -Wno-switch-default -Wno-long-long -Wno-redundant-decls -Wno-error=missing-field-initializers -I /usr/include/sai  -Wdate-time  -g -O0 -ffile-prefix-map=/sonic/src/sonic-swss=. -fstack-protector-strong -Wformat -Werror=format-security -c -o orchagent-acl_table_manager.o `test -f 'p4orch/acl_table_manager.cpp' || echo './'`p4orch/acl_table_manager.cpp
dash/dashhaorch.cpp: In member function 'bool DashHaOrch::addHaScopeEntry(const std::string&, const dash::ha_scope::HaScope&)':
dash/dashhaorch.cpp:191:6: error: stack protector not protecting local variables: variable length buffer [-Werror=stack-protector]
  191 | bool DashHaOrch::addHaScopeEntry(const std::string &key, const dash::ha_scope::HaScope &entry)
      |      ^~~~~~~~~~

What I did
Fixed compilation error